DROP TABLE IF EXISTS CDW_SAPP_D_BRANCH;
CREATE TABLE CDW_SAPP_D_BRANCH
	( 		BRANCH_CODE   STRING, 
			BRANCH_NAME   STRING, 
			BRANCH_STREET STRING, 
			BRANCH_CITY   STRING, 
			BRANCH_ZIP    STRING,
			BRANCH_PHONE  STRING,
			LAST_UPDATED  TIMESTAMP
	 )
PARTITIONED BY(BRANCH_STATE STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION'/user/maria_dev/hadoop_casestudy/CDW_SAPP_D_BRANCH'
tblproperties ("skip.header.line.count"="0");